version: '3.5'

# Services
services:

  # PHP FPM Service
  php:
    container_name: php4 # fix for containers already being in use (even tho no containers are running)
    build:
      dockerfile: ./docker/php/dockerfile
      context: .
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    container_name: web4 # see line 8
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    container_name: ${DB_NAME} # see line 8
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - './docker/mysqldata:/var/lib/mysql'

# Volumes
volumes:
  mysqldata: