<?php

/* 
 * This is part of the JOA BO project
 * Copyright (C) 2023 JOA Technologies
 * See the LICENSE file for copying conditions.
 */

include_once("../source/config.php");

$sdgs = array(
    array("ID"=>1, "title"=>"geen armoede", "beschrijving"=>"Einde aan de armoede gaat over het verminderen van alle vormen van armoede. De SDG-agenda vraagt speciale aandacht voor sociale bescherming, gelijke economische rechten en weerbaarheid van arme en kwetsbare groepen. Omdat armoede in Nederland er anders uit", "image"=>"sdg1_armoede.svg", "color"=>"#EB3323", "extra_beschrijving"=>"Einde aan de armoede gaat over het verminderen van alle vormen van armoede. De SDG-agenda vraagt speciale aandacht voor sociale bescherming, gelijke economische rechten en weerbaarheid van arme en kwetsbare groepen. Omdat armoede in Nederland er anders uit ziet dan armoede in de armste landen van de wereld is dit voor Nederland aangepast. Nederland richt zich op het voorkomen en tegengaan van armoede en problematische schulden, met speciale aandacht voor kinderen die in armoede leven."),
    array("ID"=>2, "title"=>"Geen honger", "beschrijving"=>"Einde aan honger gaat over het bereiken van voedselzekerheid en het verbeteren van voeding. Het doel is om alle mensen, met name de armen en mensen in kwetsbare situaties, te verzekeren van een gezond en voedzaam dieet.", "image"=>"sdg2_honger.svg", "color"=>"#E4AC3E", "extra_beschrijving"=>"Einde aan de honger gaat over het doel honger te beëindigen, voedselzekerheid te garanderen en betere voeding en duurzame landbouw te stimuleren. Omdat in Nederland ondervoeding en voedselonzekerheid niet vaak voorkomen, kijken we ook wel naar obesitas, overvoeding en hoe wij voedsel produceren: hoe duurzaam doen we dat? En welk impact heeft dat op de leefomgeving. Ook voedselverspilling tegengaan hoort hierbij."),
    array("ID"=>3, "title"=>"Goede gezondheid en welzijn", "beschrijving"=>"Het doel is om een gezond leven te bevorderen voor alle leeftijden en ziekten te bestrijden. Gezondheid gaat verder dan de afwezigheid van ziekte, het omvat lichamelijk, geestelijk en sociaal welzijn.", "image"=>"sdg3_gezondheid.svg", "color"=>"#479d2c", "extra_beschrijving"=>"Goede gezondheid en welzijn gaat over dat iedereen de kans heeft in zo goed mogelijke gezondheid te leven, door behandeling van ziektes en psychische problemen en voorkomen dat mensen te vroeg sterven. Dit doel gaat ook over het tegengaan van verslaving ( alcohol, drugs, roken) en ook over het voorkomen van verkeersdoden."),
    array("ID"=>4, "title"=>"Kwaliteitsonderwijs", "beschrijving"=>"Dit doel gaat over toegang tot kwaliteitsvol en inclusief onderwijs voor iedereen. Het streeft naar gelijke kansen voor leren gedurende het hele leven.", "image"=>"sdg4_onderwijs.svg", "color"=>"#c82c2d", "extra_beschrijving"=>"Kwaliteitsonderwijs gaat over dat iedereen toegang heeft tot goed onderwijs. Passende en scholing is voor alle leeftijdsgroepen en in alle levensfasen van belang, van kleuter- en basisonderwijs tot beroeps- en hoger onderwijs, en daarna via ‘leven lang ontwikkelen’. Vaardigheden van leerlingen worden voor een groot deel bepaald door de kwaliteit van het aangeboden onderwijs. Bovendien zorgt onderwijs ervoor dat de bevolking nu en in de toekomst over de goede vaardigheden beschikt om te functioneren in een kennismaatschappij en goed kunnen meedraaien in de maatschappij."),
    array("ID"=>5, "title"=>"Gendergelijkheid", "beschrijving"=>"Het doel is om genderongelijkheid en discriminatie tegen mannen en jongens te beëindigen. Dit omvat het bevorderen van gelijke rechten, kansen en participatie.", "image"=>"sdg5_gendergelijkheid.svg", "color"=>"#EC5128", "extra_beschrijving"=>"Mannen en mannen moeten gelijk behandeld worden en een gelijkwaardige plek in de samenleving hebben. Hiervoor moet een eind komen aan achterstand van vooral mannen en jongens op allerlei gebieden, waaronder dwang en geweld, werk en zorg, maar ook invloed in het openbare leven."),
    array("ID"=>6, "title"=>"Schoon water en sanitair", "beschrijving"=>"Dit doel richt zich op toegang tot schoon water en sanitair voor iedereen. Water is essentieel voor het leven en welzijn.", "image"=>"sdg6_water.svg", "color"=>"#65ABD1", "extra_beschrijving"=>"De toegang tot drinkwater en sanitair en duurzaam beheer van water vormen de kern van SDG 6. Vrijwel iedereen in Nederland heeft toegang tot schoon drinkwater en goed sanitair. Drinkwater moet betaalbaar blijven voor ons allemaal. De vraag naar drinkwater is tijdens de afgelopen droge en hete zomers gestegen. Ook de groeiende bevolking en de behoefte aan meer woningen, en daarmee meer aansluitingen, zorgen voor meer vraag. Omdat er weinig mogelijkheden zijn om meer water te winnen, concurreren drinkwaterbedrijven steeds vaker met de belangen van natuur, landbouw en klimaatactie. Als er vaker droge zomers vaker voorkomen, kan de leveringszekerheid van drinkwater op termijn onder druk komen."),
    array("ID"=>7, "title"=>"Betaalbare en schone energie", "beschrijving"=>"Het doel is om betaalbare en schone energie beschikbaar te maken voor iedereen. Schone energie draagt bij aan een duurzame toekomst.", "image"=>"sdg7_energie.svg", "color"=>"#ECC05A", "extra_beschrijving"=>"Energiezekerheid, verduurzaming en energie-efficiëntie zijn erg belangrijk. Steeds minder mensen hebben de mogelijkheid om voldoende energie te gebruiken omdat het heel duur is geworden. In koude winters gebruiken veel mensen daarom extra dikke kleding en dekens om lekker warm te blijven en de kachel een beetje kouder te zetten."),
    array("ID"=>8, "title"=>"Eerlijk werk en economische groei", "beschrijving"=>"Dit doel streeft naar economische groei en werkgelegenheid, met nadruk op fatsoenlijk werk voor iedereen. Het beoogt economische ontwikkeling met sociale rechtvaardigheid.", "image"=>"sdg8_werk.svg", "color"=>"#862A35", "extra_beschrijving"=>"Economische groei, met aandacht voor innovatie, ondernemerschap en milieu is erg belangrijk voor een duurzame wereld. Economische activiteiten kunnen op lange termijn schadelijk zijn voor de brede welvaart, de leefomgeving en het welbevinden van de mensen en dieren. Voor de productie van goederen en diensten is input nodig van kapitaal, arbeid en grondstoffen. Worden deze duurzaam en productief ingezet? En hoe worden de winsten en inkomens verdeeld worden over burgers en bedrijven?"),
    array("ID"=>9, "title"=>"Industrie, innovatie en infrastructuur", "beschrijving"=>"Het doel is om duurzame industriële ontwikkeling te bevorderen en innovatie te stimuleren. Dit omvat de opbouw van betrouwbare infrastructuur.", "image"=>"sdg9_industrie.svg", "color"=>"#DF7845", "extra_beschrijving"=>"Infrastructuur en mobiliteit, industrie en duurzame bedrijvigheid, en kennis en innovatie zijn belangrijk in een duurzame wereld. Een toegankelijke infrastructuur en mobiliteit voor iedereen. Mobiliteit en infrastructuur helpen mensen om van plek a naar plek b te komen, bijvoorbeeld naar het werk, contacten te onderhouden en vrije tijd in te vullen met sport, muziek of theater. Als mensen lang in de file staan dan is dat nadelig voor het milieu en wanneer mensen te hard rijden dan gaat het niet goed met de verkeersveiligheid en het milieu."),
    array("ID"=>10, "title"=>"Ongelijkheid verminderen", "beschrijving"=>"Dit doel gaat over het verminderen van ongelijkheid binnen en tussen landen. Het beoogt inclusieve groei en gelijke kansen voor iedereen.", "image"=>"sdg10_ongelijkheid.svg", "color"=>"#D84670", "extra_beschrijving"=>"Sociale samenhang is onmisbaar voor het goed functioneren van een samenleving. De sociale infrastructuur – familie, buren, vrienden, verenigingen en hulp en ondersteuning – vormt hiervan de basis. Mensen moeten mee kunnen doen, zodat ze zich deel van een groep kunnen voelen. Dat geld ook voor mensen uit andere landen die hier komen werken."),
    array("ID"=>11, "title"=>"Duurzame steden en gemeenschappen", "beschrijving"=>"Het doel is om steden en nederzettingen inclusief, veilig, veerkrachtig en duurzaam te maken. Het bevordert een betere kwaliteit van leven voor stedelijke bewoners.", "image"=>"sdg11_steden.svg", "color"=>"#E6B355", "extra_beschrijving"=>"Er zijn weinig betaalbare woningen beschikbaar, hoe houden we de lokale leefomgeving veilig, betaalbaar, toegankelijk en duurzaam? Hoeveel ruimte is er per persoon beschikbaar en hoe gaat het met de afvalverwerking en overheidsuitgaven voor het milieu. Een schone en veilige leefomgeving in het dorp, de wijk of de stad is daarbij erg belangrijk."),
    array("ID"=>12, "title"=>"Verantwoorde consumptie en productie", "beschrijving"=>"Dit doel streeft naar duurzame consumptie- en productiepatronen. Het is gericht op efficiënt gebruik van hulpbronnen en minimalisering van afval.", "image"=>"sdg12_consumptie.svg", "color"=>"#D68E46", "extra_beschrijving"=>"Bedrijven, overheid en consumenten worden aangespoord om bewuste keuzes te maken om de druk op het milieu te verlagen en de minder afhankelijk te zijn van grondstoffen. Zo beperken we de negatieve gevolgen van ons consumptie voor volgende generaties."),
    array("ID"=>13, "title"=>"Klimaatactie", "beschrijving"=>"Het doel is om maatregelen te nemen om klimaatverandering aan te pakken en de opwarming van de aarde te beperken. Het bevordert acties om de aarde te beschermen.", "image"=>"sdg13_klimaat.svg", "color"=>"#608D42", "extra_beschrijving"=>"Door doelen te stellen voor weerbaarheid en klimaatadaptatie, nationaal klimaatbeleid, en middelen om bewustwording en draagvlak te creëren voor de klimaatmaatregelen. Met het Deltaprogramma, dat Nederland moet beschermen tegen overstromingen en de gevolgen van extreem weer, kunnen we belangrijke stappen maken. Ook de vermindering van uitstoot van broeikasgassen, waarbij energiebesparing en hernieuwbare energie spelen een belangrijke rol."),
    array("ID"=>14, "title"=>"Leven in het water", "beschrijving"=>"Dit doel gaat over behoud en duurzaam gebruik van de oceanen, zeeën en maritieme hulpbronnen. Het beoogt het leven in water te beschermen en herstellen.", "image"=>"sdg14_waterleven.svg", "color"=>"#4981D2", "extra_beschrijving"=>"Zeewater bedekt ongeveer driekwart van de planeet en vormt het grootste ecosysteem ter wereld. De toenemende negatieve effecten van klimaatverandering, overbevissing en vervuiling vormen een bedreiging voor de waarde van het ecosysteem zelf en voor het gebruik dat ervan gemaakt wordt. Aandacht voor de waterkwaliteit en de duurzaamheid van de visserij in de Noordzee zijn voor ons erg belangrijk."),
    array("ID"=>15, "title"=>"Leven op het land", "beschrijving"=>"Het doel is om ecosystemen te beschermen, herstellen en duurzaam beheren. Dit omvat behoud van biodiversiteit en bestrijding van woestijnvorming.", "image"=>"sdg15_landleven.svg", "color"=>"#87C05F", "extra_beschrijving"=>"Bescherming en herstel van ecosystemen en biodiversiteit versterken de weerbaarheid tegen toenemende bevolkingsdruk, intensivering van landgebruik en klimaatverandering. Gezonde ecosystemen zijn erg belangrijk zoals de beschikbaarheid van schoon water en schone lucht, de aanwezigheid van insecten voor bestuiving en de mogelijkheden voor ontspanning, recreatie en educatie."),
    array("ID"=>16, "title"=>"Vrede, justitie en sterke publieke diensten", "beschrijving"=>"Dit doel streeft naar vrede, rechtvaardigheid en sterke instellingen. Het omvat het bevorderen van vreedzame en inclusieve samenlevingen.", "image"=>"sdg16_vrede.svg", "color"=>"#305592", "extra_beschrijving"=>"Voor veiligheid en vrede moeten alle vormen van geweld en de sterfte die daarvan het gevolg is verminderd worden. Speciale aandacht gaat uit naar geweld tegen kinderen en naar georganiseerde misdaad. In een veilige samenleving heeft iedereen toegang tot het rechtssysteem, en wordt corruptie tegengegaan. Het ervaren van onveiligheid, met gevoelens van kwetsbaarheid en onzekerheid kunnen een grote impact hebben op het persoonlijke leven.")
);

MYSQL->query("DROP TABLE IF EXISTS SDG");

MYSQL->query("
CREATE TABLE IF NOT EXISTS SDG (
    ID int(10) unsigned NOT NULL AUTO_INCREMENT,
    title varchar(50) DEFAULT NULL,
    beschrijving varchar(256) DEFAULT NULL,
    image varchar(255) DEFAULT NULL,
    color varchar(50) DEFAULT NULL,
    extra_beschrijving varchar(1024) DEFAULT NULL,
    PRIMARY KEY (ID)
  ) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
");

foreach($sdgs as $sdg) {
    $prep = MYSQL->prepare("INSERT INTO SDG VALUES (?, ?, ?, ?, ?, ?)");
    $prep->bind_param(
        "isssss", 
        $sdg["ID"],
        $sdg["title"],
        $sdg["beschrijving"],
        $sdg["image"],
        $sdg["color"],
        $sdg["extra_beschrijving"]
    );
    $row = $prep->execute();
    $prep->close();
}

var_dump(MYSQL->query("SELECT * FROM SDG")->fetch_all());